### ISSUE TITLE
choose a different name, becaue it's already taken

### ISSUE THREAD

**Issue by szuecs** [concur/skipper#9]
https://github.com/zalando/skipper is already a http router library, binary and Kubernetes ingress implementation, which is since >2y open source.
It makes sense that you change the name to be not ambiguous.

Thanks and best

**Comment by emaildanwilson** [comment]
zalando/skipper looks interesting! I'll have to try it out.

We've been using the name skipper internally for a few years too so changing the name now wouldn't be easy for us. I'm ok with the names staying the same since they are in different product areas.  If for some reason this project becomes popular and there ends up creating obvious confusion to k8s users I'd be happy to revisit this.

By the way, several other projects have selected the name `skipper` as well as you can see below. This is not a holistic list just a few a selected from a quick search.

balderdashy/skipper - express framework plugin - 2014
cameronmaske/skipper - docker + coreos orchestration - 2014
Stratoscale/skipper - tool to dockerize git repos - 2016
